spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: MANUAL

rabbitmq:
  queue:
    reservation-created: ${RABBITMQ_QUEUE_RESERVATION_CREATED:reservation.created}
    reservation-cancelled: ${RABBITMQ_QUEUE_RESERVATION_CANCELLED:reservation.cancelled}
    reservation-revoked: ${RABBITMQ_QUEUE_RESERVATION_REVOKED:reservation.revoked}
    reservation-approved: ${RABBITMQ_QUEUE_RESERVATION_APPROVED:reservation.approved}
    dlq: ${RABBITMQ_QUEUE_DLQ:reservation-dead-letter-queue}
  exchange:
    reservations: ${RABBITMQ_EXCHANGE_RESERVATIONS:reservations.exchange}
    dlx: ${RABBITMQ_EXCHANGE_DLX:reservations.dlx}
  message:
    ttl: ${RABBITMQ_MESSAGE_TTL:60000}

server:
  port: 8084

logging:
  level:
    com.example.notificationservice: INFO
    org.springframework.amqp: DEBUG
