server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://faculty-db:5432/faculty
    username: faculty
    password: faculty
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:mysecretkeymysecretkeymysecretkey}

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}

scheduling:
  service:
    base-url: http://scheduling-service:8080
reservation:
  service:
    base-url: http://reservation-service:8080