server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://scheduling-db:5432/scheduling
    username: scheduling
    password: scheduling
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: mysecretkeymysecretkeymysecretkey