server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://reservation-db:5432/reservation}
    username: ${SPRING_DATASOURCE_USERNAME:reservation}
    password: ${SPRING_DATASOURCE_PASSWORD:reservation}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:mysecretkeymysecretkeymysecretkey}


scheduling:
  service:
    base-url: ${SCHEDULING_SERVICE_BASE_URL:http://scheduling-service:8080}